package com.example.seleniumide;
// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

public class TestCalcolo{
    //test generato da selenium ide, il test si collega alla calcolatrice di google, svolge diverse operazioni,
    //prende il risultato di queste operazioni (in questo caso mi aspetto di ricevere 100 come risultato) e
    // gli sottraggo 20, e vedo se il risultato atteso (80) sia effettivamente anche quello trovato
    private WebDriver driver;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        //driver firefox fornito insieme ai 2 test
        System.setProperty("webdriver.gecko.driver","/Users/mauriziore/Desktop/driverFirefox/geckodriver");
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
    }
    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void calco() throws InterruptedException {
        driver.get("https://www.google.com/search?q=calcolatrice+online&client=firefox-b-d&ei=T3riY5rpAtyQxc8PtN-XoA4&oq=ca&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQARgAMgoIABCxAxCDARBDMgoIABCxAxCDARBDMgsIABCABBCxAxCDATILCAAQgAQQsQMQgwEyCAguEIAEENQCMgQIABBDMgQIABBDMggIABCABBCxAzILCAAQgAQQsQMQgwEyDgguEIAEELEDEMcBENEDOgUIABCABEoECEEYAEoECEYYAFDfBViCCmDLEWgCcAF4AIABoAKIAekDkgEDMi0ymAEAoAEBsAEAwAEB&sclient=gws-wiz-serp");
        driver.findElement(By.xpath("/html/body/div[3]/div[3]/span/div/div/div/div[3]/div[1]/button[1]/div")).click();
        Thread.sleep(3000);
        driver.manage().window().setSize(new Dimension(967, 699));
        driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(1) > .A2W7l > .XRsWPe")).click();
        driver.findElement(By.cssSelector("tr:nth-child(5) .A2W7l > .XRsWPe")).click();
        driver.findElement(By.cssSelector("tr:nth-child(3) .mF5fo > .XRsWPe")).click();
        driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(3) > .A2W7l > .XRsWPe")).click();
        driver.findElement(By.cssSelector("tr:nth-child(4) .mF5fo > .XRsWPe")).click();
        driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(2) > .A2W7l > .XRsWPe")).click();
        driver.findElement(By.cssSelector("tr:nth-child(5) .A2W7l > .XRsWPe")).click();
        driver.findElement(By.cssSelector(".UUhRt")).click();
        WebElement box= driver.findElement(By.id("cwos"));
        int risultatoAspettato=Integer.parseInt(box.getText());
        Assert.assertEquals(risultatoAspettato-20,80);
    }
}